### PR TITLE
Fix compilation on R-devel

### LINKED ISSUE #467: Compilation fail macOS 13 (R 4.5)
Hello there!

I'm getting a build fail during [macOS 13 (devel)](https://github.com/albersonmiranda/fio/actions/runs/10538588481/job/29208097258) CI:

```
✖ Failed to build fs 1.6.4 (1.9s)
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package fs.
  Full installation output:
  * installing *source* package ‘fs’ ...
  ** package ‘fs’ successfully unpacked and MD5 sums checked
  staged installation is only possible with locking
  ** using non-staged installation
  ** libs
  using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.1.0.2.5)’
  using SDK: ‘’
  clang++ -arch x86_64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./libuv-1.44.2/include -I. -pthread  -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic  -c dir.cc -o dir.o
  clang++ -arch x86_64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./libuv-1.44.2/include -I. -pthread  -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic  -c error.cc -o error.o
  In file included from error.cc:1:
  In file included from ./error.h:5:
  In file included from /Library/Frameworks/R.framework/Resources/include/Rinternals.h:47:
  In file included from /Library/Frameworks/R.framework/Resources/include/R_ext/Error.h:30:
  In file included from /Library/Frameworks/R.framework/Resources/include/R_ext/RS.h:30:
  /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstring:117:1: error: templates must have C++ linkage
  template <class _Tp>
  ^~~~~~~~~~~~~~~~~~~~
  /Library/Frameworks/R.framework/Resources/include/Rinternals.h:37:1: note: extern "C" language linkage specification begins here
  extern "C" {
  ^
  1 error generated.
  make: *** [error.o] Error 1
  ERROR: compilation failed for package ‘fs’
```
I've tried deleting the cache, but the error persisted. I'm not sure if it's on your side, but I thought it was worth reporting.

### PR DESCRIPTION
**Pull request by gaborcsardi**
Probably broken by https://github.com/wch/r-source/commit/d5776bdfaef6910a878650c86aa5bcf9f758b453#diff-a78d608840ce8dd8732ff281aa99024262e44b5e372e58f3f7c6b858fce270e6R30

Fixes #467.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
The CI still fails because xml2 has the same issue, but now fs is installing cleanly, so I am going to merge this and fix xml2 later.
