### ISSUE TITLE
Compilation fail with R 3.6.3

### ISSUE THREAD

**Issue by carsteen** [r-lib/fs#249]
Hello,

I am getting this error after upgrading R from from 3.4 to 3.6.3 when reistalling fs 1.3.2 among other packages :   

```g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c id.cc -o id.o
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:77:0,
                 from id.cc:1:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/Rmath.h: In function ‘double R::pythag(double, double)’:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/Rmath.h:222:55: error: ‘::Rf_pythag’ has not been declared
     inline double pythag(double a, double b) { return ::Rf_pythag(a, b); }
                                                       ^
/usr/lib/R/etc/Makeconf:175 : la recette pour la cible « id.o » a échouée
make: *** [id.o] Erreur 1
ERROR: compilation failed for package ‘fs’
```
I also tried to install previous version by packaging myself from your github 1.3.1 sources but got the very same error.

```> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
 [4] LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3 
```

Thanks for your time

**Comment by jimhester** [comment]
This seems like an issue in Rcpp rather than in fs. From https://github.com/RcppCore/Rcpp/issues/871#issuecomment-431576829 it seems like this was removed in more recent versions of Rcpp, so I think upgrading Rcpp before installing fs should resolve the issue.

**Comment by carsteen** [comment]
Indeed. Thank you !
